version: "2"
services:
  backend:
    build: .
    ports:
    - "8080:8080"
    environment:
      hostname: "http://docker.for.mac.host.internal:4001"
      channel: "mychannel"
      chaincode: "emrcc"
      chaincodeVer: "v1"
      dbName: "mysql"
    depends_on:
    - mysql
  mysql:
    build: mysql/
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: myimagedb

      