apiVersion: v1
kind: Service
metadata:
  name: hc-bc-backend
spec:
  type: LoadBalancer
  selector:
    app: hc-bc
  ports:
  - name: backend-port
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-bc-backend
  labels:
    app: hc-bc
spec:
  selector:
    matchLabels:
      app: hc-bc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hc-bc
    spec:
      containers:
      - name: backend
        image: schmidtp0740/hc-bc-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: "hostname"
          value: "http://129.213.52.239:4001"
        - name: "channel"
          value: "test1.emr.channel"
        - name: "chaincode"
          value: "emrcc-test"
        - name: "chaincodeVer"
          value: "v1"
        - name: "dbName"
          value: hc-bc-mysql